martinus/unordered_dense

include/ankerl/unordered_dense.h
test/bench/quick_overall_map.cpp
test/meson.build
test/unit/bucket.cpp
test/unit/max.cpp

fixes #16 by providing customizable bucket type. `bucket_type::default` and `bucket_type::big` if you really need >2^32 entries.

2022 08 custom bucket types

---

include/ankerl/unordered_dense.h
test/app/stacktrace.cpp
test/meson.build
test/unit/bucket.cpp
test/unit/max.cpp

* Fix capacity, rehash issues when bucket gets full
* Make sure uint16_t types work in bucket
* Maximum capacity is now 2^63 for bucket_type::big
* Fix bad hash for 32bit builds

Plenty of fixes when capacity is reached

---

CMakeLists.txt
README.md
include/ankerl/unordered_dense.h
meson.build
test/meson.build
test/unit/custom_hash.cpp
test/unit/namespace.cpp
test/unit/std_hash.cpp

Removes is_avalanching from default implementation that uses std::hash. That would inherit the is_avalanching when the user creates a specialization.
Adds an example test with custom hashes.
Describes hashing in the README.md in a special section, with examples

fixes is_avalanching default, adds documentation for hashing

---

README.md
test/unit/transparent.cpp

Now with documentation in README.md. Also updated transparent.cpp example and improved tests

Document heterogenous lookup using `is_transparent`

---

CMakeLists.txt
include/ankerl/unordered_dense.h
meson.build
scripts/lint/lint-version.py
test/unit/namespace.cpp
test/unit/transparent.cpp

Implements heterogeneous overloads for various additional methods. Previously, only "P1690R1 Refinement Proposal for P0919 Heterogeneous lookup for unordered containers" was implemented.
This adds overloads for map:
* try_emplace
* insert_or_assign
* operator[]
* at
and for set:
* insert
* Additionally, emplace() was updated too to work too.

Support heterogeneous C++26 overloads

---

CMakeLists.txt
include/ankerl/unordered_dense.h
meson.build
test/unit/custom_container.cpp
test/unit/custom_container_boost.cpp
test/unit/namespace.cpp

Previously I (wrongly) used containers for the construction of maps when a custom container was specified. That's not really how it is intended, the parameter should still be an allocator.
This fixes that issues, so now its possible to copy/move etc. maps when a custom container is used. That container needs the constructors that accept an allocator.
I had to bump version by a major number to 2.0.0 because this is an incompatible API change.

Fix constructors for custom container

---

CMakeLists.txt

In some modern build processes, some tools (e.g. vcpkg) do not display the names under ``/usr/share/unordered_dense/cmake`` correctly, but ``/usr/lib64/cmake/unordered_dense`` works fine.
In many distributions, most libraries are installed to ``/usr/lib64/cmake/<EXPORT_NAME>``, including header only libraries.

CMakeLists.txt: fix .cmake install path for better compatibility

---

include/ankerl/unordered_dense.h
test/unit/ctors.cpp

Also make it work when the underlying container doesn't have a reserve(), e.g. for std::deque.

Use reserve() in table's constructor

---

CMakeLists.txt
include/ankerl/unordered_dense.h
meson.build
test/meson.build
test/unit/namespace.cpp
test/unit/set_or_map_types.cpp

This should help e.g. serializers who want to distinguish between map and set by checking for mapped_type. Also, it's more correct.

Make mapped_type only available for map, not for set

---

CMakeLists.txt
include/ankerl/unordered_dense.h
meson.build
scripts/lint/lint-clang-format.py
test/bench/copy.cpp
test/bench/find_random.cpp
test/bench/quick_overall_map.cpp
test/bench/swap.cpp
test/unit/namespace.cpp
test/unit/unordered_set.cpp

This is the same as for std::unordered_set. Bump version to 3.0.0 due to incompatible API change.
Also, some minor cleanup.

unordered_dense::set iterator is now const_iterator

---

include/ankerl/unordered_dense.h
test/unit/pmr.cpp

Until LLVM 16 is released, and until Android and Apple platforms incorporate the forthcoming std::pmr support in their forks of libc++, this workaround is needed to use pmr containers on those platforms.

add libc++ compatibility by checking for <experimental/memory_resource>

---

.github/workflows/main.yml
CMakeLists.txt
include/ankerl/unordered_dense.h
meson.build
test/app/stacktrace.cpp
test/meson.build
test/unit/namespace.cpp
test/unit/pmr.cpp
test/unit/pmr_move_with_allocators.cpp

m_buckets can only be reused when the allocators are equal. Otherwise we would deallocate with m_buckets with the incorrect allocator.
Also bumped the version for the fix.

fix #79: don't reuse m_buckets when allocator does not compare equal

---

.github/workflows/main.yml
CMakeLists.txt
include/ankerl/unordered_dense.h
meson.build
scripts/build.py
scripts/lint/lint-clang-format.py
test/bench/game_of_life.cpp
test/bench/quick_overall_map.cpp
test/bench/show_allocations.cpp
test/meson.build
test/unit/bucket.cpp
test/unit/ctors.cpp
test/unit/namespace.cpp
test/unit/pmr.cpp

Fixes #98. This changes the behavior of unordered_dense:
* Now an initial map allocates. So creating & never using a bunch of maps will have more overhead - That's not something I optimize for though.
* `operator[]`, or `try_emplace` doesn't increase size when the element is found. Basically I had to shift an `if` to another place, so performance wise there shouldn't be much of a difference. Maybe it's even faster.

dont resize in emplace when not necessary

---

CMakeLists.txt
include/ankerl/unordered_dense.h
meson.build
test/meson.build
test/unit/namespace.cpp
test/unit/tuple_hash.cpp

Instead of sequentially hashing one element after the other, this puts all data into a temporary std::array and hashes this buffer. The compiler can see through all of that and produce highly optimized code.

Provide high quality & fast hash implementations for std::tuple and std::pair

---

include/ankerl/unordered_dense.h
scripts/build.py
test/unit/tuple_hash.cpp

Slightly improved tuple hash, now direct also for enum.

---

CMakeLists.txt
README.md
include/ankerl/unordered_dense.h
meson.build
test/unit/extract.cpp
test/unit/namespace.cpp
test/unit/tuple_hash.cpp

Similar to erase(), but the return value is the erased element, moved out.
This has practically the same performance behavior as erase(), except
for 2 additional moves. (once into a temporary variable), and then out.

Add extract(key) and extract(it) API

---

test/app/counter.h

Build error:
```
In file included from /..../unordered_dense/test/app/counter.cpp:1:
/..../unordered_dense/test/app/counter.h: In function 'bool operator==(const counter::data_t&, const counter::data_t&)':
/..../unordered_dense/test/app/counter.h:31:30: error: 'memcmp' is not a member of 'std'; did you mean 'wmemcmp'?
31 |             return 0 == std::memcmp(&a, &b, sizeof(data_t));
|                              ^~~~~~
```

Fix build with current fmt (master branch)

---

.clang-tidy

When running clang-tidy (17.0.6-5; alma linux 9.4) the current configuration emits an error about a duplicate entry.  Personally I think clang should handle that nicer but this removes the duplicate entry.
```
_deps/unordered_dense-src/.clang-tidy:49:3: error: duplicated mapping key 'readability-identifier-naming.PrivateMemberPrefix'
readability-identifier-naming.PrivateMemberPrefix: 'm_'
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Remove duplicate clang-tidy line

---

include/ankerl/unordered_dense.h
test/app/doctest.h
test/unit/custom_container.cpp

In segmented mode we only applied the segmenting to the values array but
not the bucket array.
As a result there the pattern of there still being a deallocation
followed by an increased allocation when resizing the hash map
continues to exist.
Further, in environments where the max allocation size is limited
because of fragmentation issues this can lead to problems.
To avoid both of these issues this patch makes the bucket array use the
same datastructure as the values array, i.e.: a `std::vector` when
linear and `segmented_vector` when segmented (or the passed
datastructure if specified).
This extra indirection does add some overhead in the segmented case.
Looking at the quick benchmarks we see:
Before:
```
|               ns/op |                op/s |    err% |          ins/op | …
```

segment_map: Also segment the bucket array

---

include/ankerl/unordered_dense.h

If a `std::hash` specialisation has `using is_avalanching = void;` pass this through to `unordered_dense::hash` this avoids duplicating a hash function for a custom type if you want it to work for generic stl containers and unordered_dense with a correct avalanche tag.

Passthrough is_avalanching from std::hash

---

include/ankerl/unordered_dense.h

Currently, `segmented_vector::iter_t` lacks the post-increment operator. It may be nice to have and only requires a few lines of code.

Add iter_t::operator++(int) overload

---

CMakeLists.txt
include/ankerl/unordered_dense.h
meson.build
scripts/build.py
test/unit/ctors.cpp
test/unit/namespace.cpp
test/unit/pmr.cpp
test/unit/windows_include.cpp

also adds `-std=c++23` compile to the local build script

Adds `ANKERL_UNORDERED_DENSE_DISABLE_PMR`, bumps version

---

include/ankerl/unordered_dense.h

- fix move constructor (use of uninitialized allocator)
- fix constness in iter_t operators +(diff), -(iter)
- make iter_t random access
I adopted this class in my project just as a replacement for deque and found some problems.

minor segmented_vector fixes

---

include/ankerl/unordered_dense.h

They crop up on valid per the standard (but sometimes bogus) uses
of modular arithmetic on unsigned integers, such as in hash functions.

Disable ubsan's integer sanitizer warnings

---

include/ankerl/unordered_dense.h

unordered_dense.h fails to compile on Windows/MinGW with GCC >= 13 with thread model win32, and _WIN32_WINNT < 0x600 (Vista), in CFLAGS/CXXFLAGS.  E.g., GDB defines _WIN32_WINNT to 0x501, and it fails to build with GCC 14.2 like so:
CXX    ada-exp.o
In file included from /opt/xpack-mingw-w64-gcc-14.2.0-1/x86_64-w64-mingw32/include/c++/14.2.0/shared_mutex:42,
from /opt/xpack-mingw-w64-gcc-14.2.0-1/x86_64-w64-mingw32/include/c++/14.2.0/memory_resource:66,
from /home/pedro/gdb/src/gdb/../gdbsupport/unordered_dense.h:104,
from /home/pedro/gdb/src/gdb/../gdbsupport/unordered_map.h:21,
from /home/pedro/gdb/src/gdb/gdbtypes.h:53,
from /home/pedro/gdb/src/gdb/expression.h:23,
from /home/pedro/gdb/src/gdb/ada-exp.y:40:
/opt/xpack-mingw-w64-gcc-14.2.0-1/x86_64-w64-mingw32/include/c++/14.2.0/bits/std …

Fix MinGW build with _WIN32_WINNT<0x600, GCC>=13, model=win32

---

include/ankerl/unordered_dense.h

Unfortunately had to add another macro for it, since the attribute needs to be placed after the last bracket of the condition.
Maybe we can combine it into a single macro with some hackyness. Let me know what you'd prefer

Add support for c++20 likely/unlikely attributes
